### ISSUE TITLE
Three builds files are out of date with latest three.js build

### ISSUE THREAD

**Issue by meesrutten** [pmndrs/react-three-next#16]
Hi 👋,
The exports in the files in three_builds are out of date.
For example, Face3D.js and Geometry.js were removed from Three.js but still present in the files in this stack.
This issue leads to build and export errors.

https://github.com/pmndrs/react-three-next/blob/main/src/examples/three_builds/

**Comment by RenaudRohlinger** [comment]
@meesrutten Thanks for the feedback. I updated the builds to the last version and tested it should be good now.

The custom builds are just a copy of this file:
https://github.com/mrdoob/three.js/blob/dev/src/Three.js

I changed the three_minimal configuration because now the starter depends on Drei which include most of the elements of threejs. You can easily comment the exports that are not needed in three_minimal and try to yarn build to check if anything breaks. Also it's possible to check the size of the custom build you made with "yarn analyze".
