### ISSUE TITLE
Any plans to support TypeScript?

### ISSUE THREAD

**Issue by geoyws** [pmndrs/react-three-next#22]
Thank you guys so much for the work that you do.

Are there any plans to support TypeScript?

**Comment by RenaudRohlinger** [comment]
Thanks @geoyws! That was a big question recently we wanted to do it but since it's a starter we concluded it should be as accessible as possible even for beginners.

The best solution would be to make a typescript branch if you're down for that? I will help you if needed but I can't maintain both languages at the same time by myself.

I took into consideration the ability to easily generate a typescript starter, so if you create a typescript branch named `next-ts` on this repo you will be able to do:
`yarn create r3f-app next-ts my-start`

If you are willing to work on the Typescript starter there is more than half the r3f community that would be interested:
https://twitter.com/onirenaud/status/1375737135102263304

I would be happy to add you as a maintainer if you want to do it!

**Comment by dustinlacewell** [comment]
All it took to "convert" the project to Typescript, was to add an empty `tsconfig.json`, run `yarn dev`, Next automatically fills the `tsconfig.json` with the right settings.

All I had to do was copy the path alias settings. Your current `jsconfig.json` config is basically valid `tsconfig.json` configuration.

All of the existing code is already valid TypeScript as Javascript is a subset. I'm not sure maintaining a separate branch is exactly required. You might just tell people how to do it.

**Comment by dustinlacewell** [comment]
Here are the steps to get the current project working with typescript:

- touch `tsconfig.json`
- start the dev server, next will fill the tsconfig.json and tell you to install typescript
- `yarn add --dev typescript @types/react`
- copy the path aliases from `jsconfig.json` to `tsconfig.json`

Since javascript is a subset of typescript everything else just works!

**Comment by geoyws** [comment]
Apologies I have too much on my plate at the moment and can't afford the time. I hope someone else might be able to take this on.

**Comment by shuta13** [comment]
@RenaudRohlinger cc @geoyws 

If no one else is assigned, can I work on this issue?

**Comment by RenaudRohlinger** [comment]
Thank you very much @shuta13! As I mentioned in #37 I made a CLI tool (https://github.com/RenaudRohlinger/create-r3f-app) that allows us to clone a clean version of a branch from this repo with some small extra (when you do yarn create r3f-app next). With that tool, we could make another branch (typescript) so when you do yarn create r3f-app next typescript for example it would automatically clone the typescript branch.
I think it would imply to always keep the typescript branch up to date which is kind of hassle.

The other option (the best one imo) would be to do a small binary that uses something like execa and that would batch replace all the js files with ts extensions and then execute the following commands:

create a tsconfig.json file
yarn add --dev typescript @types/react
yarn build to generate a tsconfig.json from next or pick the template from next
copy the path aliases from jsconfig.json to tsconfig.json
Since the number of actions to do is pretty small, the script option is the way to go imo. We could host it on create-r3f-app and simply execute it if there is the "typescript" parameter.

**Comment by dustinlacewell** [comment]
It's always going to be better to just maintain the library _in_ typescript if maintainers can rise to the challenge. This way, you are getting both typescript and javascript support for the price of one. When the project is in javascript, someone has to continuously go through the process of maintaining the type specification... might as well just write the program typed.

**Comment by shuta13** [comment]
@RenaudRohlinger 

Sorry for the late reply.

I have checked about https://github.com/RenaudRohlinger/create-r3f-app. I think that creating a new "typescript" branch would satisfy the requirement, but I also think that it would be better if all js files are replaced with ts files when the "typescript" parameter is passed.

I would like to create a PR with this implementation!

**Comment by RenaudRohlinger** [comment]
It's official, @shuta13 added the typescript support !! 👏👏👏
