### ISSUE TITLE
styled-components setup missing proper babel config

### ISSUE THREAD

**Issue by cjimmy** [pmndrs/react-three-next#64]
Per the [s-c docs](https://styled-components.com/docs/tooling#usage), `babel-plugin-styled-components` needs a babel config, and because it will [override Next's babel config,](https://nextjs.org/docs/advanced-features/customizing-babel-config) we'll need to include the `next/babel` preset.

minimally, `.babelrc` should be this:
```
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", {"ssr": true}]]
}
```

`ssr: true` since Next is made for SSR (although, it may be `true` by default?)

Note that adding a babel config will force Next 12 to use babel to transpile instead of SWC, which may be undesirable for some folks. Until Next ports it all over, which it seems it is [currently working on](https://github.com/vercel/next.js/issues/30802), it has to be this way for styled-components + Next 12.

Happy to submit a PR if you point me in the right direction!

(ps. Thanks for making this starter! Really helped me out)

**Comment by RenaudRohlinger** [comment]
Thanks @cjimmy! After a week of development on different setups, I agree that SWC is still too experimental. I did try to use it by adding  :
```
  experimental: {
    styledComponents: true,
  },
```
But it seems to be still too experimental. I will revert the default .babelrc. Also, I don't think we should override the styled-components parameters and let the developer handle it to prevent unexpected behaviors (and I guess it should be true by default hopefully). 

Let's try again once this issue is closed 👀 
https://github.com/vercel/next.js/issues/30802
