### ISSUE TITLE
Loadable error when trying to use GLTF model

### ISSUE THREAD

**Issue by souporserious** [pmndrs/react-three-next#7]
Hello, first, thank you for such an awesome starter for Next! I'm currently running into an issue when trying to load a GLTF component generated from GLTFJSX. I'm trying to use [this model](https://www.cgtrader.com/free-3d-models/electronics/audio/electric-guitar-v-style) currently and import it similar to the default Sphere. However, upon loading I keep getting this error no matter the model I try to load:

![image](https://user-images.githubusercontent.com/2762082/105610477-956d1980-5d64-11eb-8f84-8182016dd4fe.png)

Any ideas on what might be causing this? You can see my [current code here](https://github.com/souporserious/guitar-shop). I was able to load the model on a Gatsby R3F starter which leads me to thinking this is NextJS specific. Any help is greatly appreciated! 🙏

**Comment by RenaudRohlinger** [comment]
Hello! Because you are loading using a dynamic component it's overriding the error. 
I fixed your example without using dynamic component, this is the working index.js : 
```
import { Suspense } from 'react'
import useStore from '@/helpers/store'
import Model from '@/components/canvas/Guitar'

const Guitar = () => {
  return (
    <Suspense fallback={null}>
      <ambientLight />
      <Model />
    </Suspense>
  )
}
const Page = () => {
  useStore.setState({ title: 'Sphere' })
  return (
    <>
      <Guitar r3f />
    </>
  )
}

export default Page

```

After that, it was possible to debug and it would just notify that you missed a Suspense since you're loading some data. So here is your example fixed with a dynamic component for better performances :
```
 
 import dynamic from 'next/dynamic'

const Model = dynamic(() => import('@/components/canvas/Guitar'), {
  ssr: false,
})

const Guitar = () => {
  return (
    <Suspense fallback={null}>
      <ambientLight />
      <Model />
    </Suspense>
  )
}
const Page = () => {
  useStore.setState({ title: 'Sphere' })
  return (
    <>
      <Guitar r3f />
    </>
  )
}

export default Page
```
(I also added a light since it's not by default you would have seen a black screen otherwise)

**Comment by souporserious** [comment]
Woot 🎉 this works great now! Thank you so much for the detailed answer! 🤗
