### ISSUE TITLE
Broken demo in development mode

### ISSUE THREAD

**Issue by andres-calvo** [pmndrs/react-three-next#82]
Hello, I created an app using this command
yarn create r3f-app next my-app styled -ts

Then in the index page it says that if i click de box it should go to the box page, but it doesnt. Also the events like onPointerOver and onPointerOut are not getting called.

Finally when I start the app in development mode it display this warning on the vscode terminal.

`(node:16492) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use "node --trace-deprecation ..." to show where the warning was created)
Defining routes from exportPathMap
(node:16492) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.`

**Comment by RenaudRohlinger** [comment]
This warning is related to the service worker package and should be harmless:
https://github.com/hanford/next-offline

I updated the CLI tool in order to fix styled-components with typescript:
https://github.com/utsuboco/create-r3f-app/commit/2b91093bd071612b0f1d95d8a6a490e962281c13

The issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/59765

It should now work if you try to install it again. Otherwise you can just update react to the latest version with `yarn add react` 👍
